### ISSUE TITLE
Spec Algorithm Issues

### ISSUE THREAD

**Issue by dj2** [fedidcg/FedCM#209] opened 2022-02-24 21:31 UTC
When updating to the new API there are a few mistakes in the algorithms. In the `get` section:

* Step 8: if mode is required the result should be a un-consented credential object
* Step 11: a un-consented credential object should be returned

**Comment by cbiesinger** [comment] 2022-02-24 21:34
To clarify the issue here, as of right now step 8 requires an HTTP request and step 11 requires UI + HTTP request, and those are undesirable.

**Comment by cbiesinger** [comment] 2022-02-24 21:34
Should also do s/teh/the/

**Comment by cbiesinger** [comment] 2022-02-24 21:35
I'm not sure if this counts as part of the algorithm, but earlier in this section:

> hint
>  Optional accountId hint. Maybe used by the UA when displaying the

That sentence is incomplete.

**Comment by samuelgoto** [comment] 2022-03-01 22:43
> Step 11: a un-consented credential object should be returned

The current spec calls [create-credential](https://fedidcg.github.io/FedCM/#create-credential) during the `get()` [algorithm](https://fedidcg.github.io/FedCM/#browser-api-federated-credential) on step (11) which at some point calls the [select an account](https://fedidcg.github.io/FedCM/#select-an-account) which at some point calls "display an account chooser". 

Meaning that, as currently spec-ed, `get()` prompts the user.

Is that a bug or working as intended? Are we supposed to prompt the user at `login()` instead?

**Comment by npm1** [comment] 2022-08-25 21:57
I don't see any of the referenced points in this issue, and the algorithms have been rewritten, so I think it is safe to close this issue.

**Closed by npm1** 2022-08-25 21:57 UTC
