### ISSUE TITLE
Explicitly allow arbitrary request content to the identity assertion endpoint

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [fedidcg/FedCM#443] opened 2023-02-16 14:25 UTC
We kind of already allow this via the nonce, however it could be useful to codify this more explicitly. Especially as this would allow inclusion of scopes being requested without having to smuggle them in via the URL of the auth endpoint or in the nonce.

I discussed something related to this in https://github.com/fedidcg/proposals/issues/3 but it could be adapted here. I'll add a comment with a general shape of the proposal.

**Comment by bvandersloot-mozilla** [comment] 2023-02-16 15:34
This would entail:

1. Adding a field to `IdentityProviderConfig`, `USVString assertion_request;` 
2. Modifying `fetch an identity assertion` to append to `|requestBody|` "&config_request=" and `|config|`'s `assertion_request`.

Overall this change is quite small and does not change the security properties. Names are only suggestions.

**Comment by samuelgoto** [comment] 2024-05-13 18:45
@cbiesinger @bvandersloot-mozilla  I'm wondering if we could/should make this a duplicate of https://github.com/fedidcg/FedCM/issues/556? wdyt?

**Comment by cbiesinger** [comment] 2024-05-13 20:09
sgtm

**Comment by samuelgoto** [comment] 2024-05-13 21:11
Ok, @bvandersloot-mozilla I'm going to mark this as a duplicate of #556 . Feel free to reopen if you feel like there is something else here that isn't captured there.

**Closed by samuelgoto** 2024-05-13 21:11 UTC
