### ISSUE TITLE
add FedCM metadata to .well-known/openid-configuration

### ISSUE THREAD

**Issue by dickhardt** [fedidcg/FedCM#251] opened 2022-04-09 20:08 UTC
Given that all large IdPs have a .well-known/openid-configuration file that has provider configuration, why not add the FedCM metadata to the openid-configuration?

This would simplify deployment for most IdPs as they are just added metadata to an existing file.

the id_token_endpoint name is name as IdPs already have an token_endpoint

I agree that id_token_endpoint should be a different endpoint than the OAuth based token_endpoint as the IdP as the payload and authentication are quite different -- but the name is confusing. Perhaps fedcm_token_endpoint?

**Comment by gffletch** [comment] 2022-04-15 17:22
Given FedCM is it's own unique protocol.. I agree with a name that doesn't leverage id_token or reference other OpenID related artifacts.

**Comment by samuelgoto** [comment] 2022-04-30 07:39
It occurred to us to try to re-use the `.well-known/openid-configuration` but that didn't seem the best choice for a couple of reasons:

(a) FedCM needs to support SAML too and
(b) We heard from IDPs that it would be useful to have the level of indirection / de-coupling so that IDPs could keep these concerns (e.g. their OIDC deployment and the integration with the browser) separately 

I'm going to tentatively close this with this resolution, feel to re-open if you disagree and we'll go from there.

**Closed by samuelgoto** 2022-04-30 07:39 UTC

**Comment by dickhardt** [comment] 2022-06-06 05:40
I agree it makes sense to be a different configuration than openid-configuration so that supporting something like SAML is possible. :)

I continue to have the strong opinion the file should be in .well-known

**Comment by yaderjaw** [comment] 2022-06-06 06:09
> أوافق على أنه من المنطقي أن يكون تكوينًا مختلفًا عن تكوين openid بحيث يكون دعم شيء مثل SAML ممكنًا. :)
> 
> ما زلت أملك رأيًا قويًا في أن الملف يجب أن يكون بتنسيق. معروف جيدًا

Duplicate of #
